/*--------------------------------------------------------------------------*/
/** \file     os_io_tables.c
*   \brief    Functions of operating system for initialization
*             and access to ports and pins of processor
*
*   \date     2024-08-22    \author   DS/
*
*   \platform HCS08DZ / HCS12XE / HCS12XD / HCS12P
* --------------------------------------------------------------------------*/


#include "os_io_tables.h" 
#include "bios_io.h" 



/** \ingroup io
*   \brief           Definition of port pins
* --------------------------------------------------------------------------*
*                    All the used pins with their initialization values are
*                    inserted in this table. The write- and read-functions
*                    #os_digin() and #os_digout() use the pin name as parameter.
*                    Output pins have to be inserted below the line
*                    #OS_PORT_INPUT_PIN_MAX
*                    Inputs and outputs could be debounced as high-low as well as
*                    low-high edges. One cycle is one call of #os_update_digin()
*                    or #os_update_digout().
*
*                    IMPORTANT: After inserting new lines the enum in os_io_tables.h
*                    has to be updated!
* --------------------------------------------------------------------------*/
const os_port_pin_def os_port_pin[] = {
//                                                                                                             Debounce cycles:
//  Pin-Name              Port                  Bit                   Direction             Pull-Dir              Pull-Enable           Interrupt Edge        Interrupt-Enable      Value                 Lo-Hi                 Hi-Lo                 Multiplex             Inverted              
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//                                              (0-7)                 (PD_IN,               (PU_UP                (PE_ON                (PI_RISE              (PI_ON                (0,1)                 (0-255)               (0-255)               (0,1)                 (0,1)                 
//                                                                    PD_OUT),              PU_DOWN)              PE_OFF)               PI_FALL)              PI_OFF)                                                                                                                                                   
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
{   DI_CAN_ERR0_N         ,PORT_D               ,2                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,0                    ,0                    }, // CAN0 transceiver error Pin inverted
{   DI_CAN_ERR1_N         ,PORT_D               ,1                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,0                    ,0                    }, // CAN1 transceiver error Pin inverted
{   DI_CAN_ERR2_N         ,PORT_D               ,0                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,0                    ,0                    }, // CAN2 transceiver error Pin inverted
{   DI_KL15               ,PORT_B               ,5                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,0                    ,0                    }, // Digital Input KL15 X101 113
{   DI_KL15_GSM           ,PORT_A               ,4                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,0                    ,0                    }, // Digital Input KL15_GSM X101 105
{   DI_RPM                ,PORT_T               ,0                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,0                    ,0                    }, // Digital Input RPM X101 8
{   DI_RPM_2              ,PORT_T               ,6                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,0                    ,1                    }, // Digital Input RPM_2 X101 108
{   D_JOYST_N_SW          ,PORT_AD2             ,6                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // IO1 Digital Input on  X101 62
{   D_SEAT_SW             ,PORT_AD2             ,6                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // IO2 Digital Input on X101 60
{   D_ROADTRAV_SW1        ,PORT_AD2             ,6                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // IO3 Digital Input on X101 56
{   D_ROADTRAV_SW2        ,PORT_AD2             ,6                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // IO4 Digital Input on X101 58
{   D_AIR_CONDITIONER_SW  ,PORT_AD2             ,6                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // IO5 Digital Input on X101 81
{   D_JOYST_RW_SW         ,PORT_AD2             ,6                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // IO6 Digital Input on X101 79
{   D_JOYST_FW_SW         ,PORT_AD2             ,6                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // IO7 Digital Input on X101 77
{   D_BRAKE_SW            ,PORT_AD2             ,6                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // IO8 Digital Input on X101 75
{   DIM_I1                ,PORT_AD2             ,5                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // I1 Digital Input on X101 24
{   DIM_I2                ,PORT_AD2             ,5                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // I2 Digital Input on X101 23
{   DIM_I3                ,PORT_AD2             ,5                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // I3 Digital Input on X101 21
{   DIM_I4                ,PORT_AD2             ,5                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // I4 Digital Input on X101 19
{   DIM_I5                ,PORT_AD2             ,5                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // I5 Digital Input on X101 43
{   DIM_I6                ,PORT_AD2             ,5                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // I6 Digital Input on X101 42
{   DIM_I7                ,PORT_AD2             ,5                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // I7 Digital Input on X101 40
{   DIM_I8                ,PORT_AD2             ,5                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,1                    ,0                    }, // I8 Digital Input on X101 38
{   DI_DIX_IO_1_8         ,PORT_AD2             ,6                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,0                    ,0                    },
{   DI_DIX_I_1_8          ,PORT_AD2             ,5                    ,PD_IN                ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,DONT_CARE            ,0                    ,0                    ,0                    ,0                    },
{   OS_PORT_INPUT_PIN_MAX ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    },
{   CAN_EN0               ,PORT_B               ,3                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // CAN0 transceiver enable Pin
{   CAN_EN1               ,PORT_B               ,2                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // CAN1 transceiver enable Pin
{   CAN_EN2               ,PORT_B               ,1                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // CAN2 transceiver enable Pin
{   CAN_STB0_N            ,PORT_AD0             ,7                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // CAN0 transceiver standby Pin inverted
{   CAN_STB1_N            ,PORT_AD1             ,0                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // CAN1 transceiver standby Pin inverted
{   CAN_STB2_N            ,PORT_AD1             ,1                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // CAN2 transceiver standby Pin inverted
{   CAN_WAKE0             ,PORT_A               ,7                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,0                    ,0                    }, // CAN0 transceiver wake Pin
{   CAN_WAKE1             ,PORT_A               ,6                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,0                    ,0                    }, // CAN1 transceiver wake Pin
{   CAN_WAKE2             ,PORT_A               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,0                    ,0                    }, // CAN2 transceiver wake Pin
{   CS_A_AI               ,PORT_S               ,2                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_B_AI               ,PORT_S               ,1                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_C_AI               ,PORT_S               ,3                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_A_IO               ,PORT_B               ,6                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_B_IO               ,PORT_B               ,7                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_C_IO               ,PORT_C               ,0                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_A_OUT              ,PORT_K               ,3                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_B_OUT              ,PORT_J               ,2                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_C_OUT              ,PORT_K               ,6                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_A_TEMP             ,PORT_T               ,3                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_B_TEMP             ,PORT_T               ,2                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_C_TEMP             ,PORT_T               ,1                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_SPI_0_N            ,PORT_E               ,4                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_SPI_1_N            ,PORT_D               ,3                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_SPI_2_N            ,PORT_D               ,4                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_SPI_3_N            ,PORT_D               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   CS_SPI_RST_N          ,PORT_D               ,6                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   DO_CS_DIS0            ,PORT_A               ,0                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   DO_CS_DIS1            ,PORT_A               ,1                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   DO_CS_DIS2            ,PORT_A               ,2                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   DO_CS_DIS3            ,PORT_A               ,3                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // chip select intern
{   DO_CS_DE_RS485        ,PORT_P               ,7                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_RS485_DE,0                    ,0                    ,0                    ,0                    }, // Digital output RS485 DE chip select
{   DO_NOX                ,PORT_C               ,1                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,0                    ,0                    }, // Digital output NOX X101 114
{   DO_POWER              ,PORT_B               ,0                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // µC selfholder Pin
{   DO_PWM_O5             ,PORT_P               ,3                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,0                    ,0                    }, // O5 Digital output PWM_O5 X101 73
{   DO_PWM_O6             ,PORT_P               ,2                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,0                    ,0                    }, // O6 Digital output PWM_O6 X101 71
{   DO_PWM_O7             ,PORT_P               ,1                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,0                    ,0                    }, // O7 Digital output PWM_O7 X101 69
{   DO_PWM_O8             ,PORT_P               ,0                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,0                    ,0                    }, // O8 Digital output PWM_O8 X101 67
{   DO_SHIFT_MR_N         ,PORT_C               ,3                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // mux intern
{   DO_SHIFT_OE_N         ,PORT_H               ,6                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // mux intern
{   DO_SHIFT_SH_CP        ,PORT_C               ,4                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // mux intern
{   DO_SHIFT_ST_CP        ,PORT_H               ,7                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_INIT    ,0                    ,0                    ,0                    ,0                    }, // mux intern
{   DO_SPI_HOLD_N         ,PORT_E               ,2                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // SPI intern
{   DO_SPI_WP_N           ,PORT_E               ,3                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,1                    ,0                    ,0                    ,0                    ,0                    }, // SPI intern
{   DOM_IO1               ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // IO1 Digital Output on  X101 62
{   DOM_IO2               ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // IO2 Digital Output on X101 60
{   DOM_IO3               ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // IO3 Digital Output on X101 56
{   DOM_IO4               ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // IO4 Digital Output on X101 58
{   DOM_IO5               ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // IO5 Digital Output on X101 81
{   DOM_IO6               ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // IO6 Digital Output on X101 79
{   DOM_IO7               ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // IO7 Digital Output on X101 77
{   DOM_IO8               ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // IO8 Digital Output on X101 75
{   DOM_POWER_SENSOR_5V   ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // 5V Sensor Voltage enable/disable X101 27 & 98
{   DOM_PANEL_ON          ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // Digital Output VCC for a Panal with max 200mA on X101  111
{   DOM_OUT_CB_2          ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // Digital Output on X101 121
{   DOM_OUT_CB_1          ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // Digital Output on X101 116
{   DOM_O4                ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // O4 Output Current on X101 54
{   D_REVERSE_BUZZER      ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // O3 Output Current on X101 52
{   D_REVERSE_LIGHT       ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // O2 Output Current on X101 50
{   DO_IGN_RELAY          ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // O1 Output Current on X101 48
{   DOM_DUMMY_1           ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,1                    ,0                    }, // O2 Output Current on X101 50
{   DOX_SR                ,PORT_C               ,5                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,0                    ,0                    ,0                    ,0                    ,0                    }, // O3 Output Current on X101 52
{   WD                    ,PORT_C               ,6                    ,PD_OUT               ,DONT_CARE            ,PE_OFF               ,DONT_CARE            ,PI_OFF               ,MAGIC_NUMBER_WDI     ,0                    ,0                    ,0                    ,0                    }, // Watchdog Pin intern
{   OS_PORT_PIN_MAX       ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    },
};

// ACHTUNG: Es wurden die 4 Pins DO_PWM_O5_INA, DO_PWM_O6_INA, DO_PWM_O7_INA, DO_PWM_O8_INA ignored.



/** \ingroup io
*   \brief           Definition of analog inputs and outputs
* --------------------------------------------------------------------------*
*                    This is the list of analog inputs and outputs.
*                    You could enter a value range from Min to Max to generate
*                    an error if the value is not within the range.
*                    The errors could be masked by error filters
*                    ( #ERR_OFF, #ERR_MIN, #ERR_MAX, #ERR_MIN_MAX )
* --------------------------------------------------------------------------*/
const os_analog_pin_def os_analog_pin[] = {
//  Pin-Name              ADC-Channel           Direction             Value                 Min                   Max                   Error-Filter          Entprell-Takte        ADC-Max mV            Multiplex             Multiplex Type        Parameter 1           Samples               
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//                                              (PD_IN                (0-                   (0-                   (0-                   (ERR_OFF              (0-255)               (0-65535)             (0,1)                 (0-255)               (0-255)               (0-255)               
//                                              PD_OUT)               32767)                32767)                32767)                ERR_MIN                                                                                                                             0 Standard            
//                                                                                                                                      ERR_MAX,                                                                                                                            1-255 ms oversample   
//                                                                                                                                      ERR_MIN_MAX                                                                                                                                               
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
{   AI_CUR_CB_1           ,17                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Current of out on X101 116
{   AI_CUR_CB_2           ,16                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Current of out on X101 121
{   AI_NOX                ,6                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Current of out on X101 114
{   AI_OUT_CB_1           ,15                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11000               ,0                    ,0                    ,0                    ,0                    }, // Voltage of out on X101 116
{   AI_OUT_CB_2           ,14                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11000               ,0                    ,0                    ,0                    ,0                    }, // Voltage of out on X101 121
{   AI_SENS_PWM_O5        ,0                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Current of PWM out on X101 73
{   AI_SENS_PWM_O6        ,11                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Current of PWM out on X101 71
{   AI_SENS_PWM_O7        ,1                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Current of PWM out on X101 69
{   AI_SENS_PWM_O8        ,19                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Current of PWM out on X101 67
{   AI_T_REF              ,4                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // K_Type referenz temperature
{   AI_VCC_PANEL          ,13                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 13704               ,0                    ,0                    ,0                    ,0                    }, // Voltage VCC for a Panal with max 200mA X101  111
{   A_JOYST_POS1          ,20                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 33000               ,1                    ,0                    ,0                    ,0                    }, // Analog input on X101 102
{   A_JOYST_POS2          ,20                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 33000               ,1                    ,1                    ,0                    ,0                    }, // Analog input on X101 106
{   A_PARKING_BRAKE_SW    ,20                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 33000               ,1                    ,2                    ,0                    ,0                    }, // Analog input on X101 6
{   A_AUX1_SIGN2          ,20                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 33000               ,1                    ,3                    ,0                    ,0                    }, // Analog input on X101 7
{   AIM_CJC               ,20                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,4                    ,0                    ,0                    }, // K_Type ColdJunctionCompensation CJC
{   AIM_DUMMY_1           ,20                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,5                    ,0                    ,0                    }, // Dummy for multiplexer
{   AIM_DUMMY_2           ,20                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,6                    ,0                    ,0                    }, // Dummy for multiplexer
{   AIM_DUMMY_3           ,20                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,7                    ,0                    ,0                    }, // Dummy for multiplexer
{   AIM_KL30_2            ,3                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 35000               ,1                    ,0                    ,0                    ,0                    }, // Voltage of KL30_2 on X101 120
{   AIM_KL30_1            ,3                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 35000               ,1                    ,1                    ,0                    ,0                    }, // Voltage of KL30_1 on X101 119
{   AIM_DUMMY_4           ,3                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,2                    ,0                    ,0                    }, // Dummy for multiplexer
{   AIM_SENSOR_5V         ,3                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11008               ,1                    ,3                    ,0                    ,0                    }, // Voltage of 5V Sensor output on X101 27 & 98
{   AIM_PRESSURE          ,3                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,4                    ,0                    ,0                    }, // Pressure voltage on X102 2
{   A_CNG_PRESSURE        ,3                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,5                    ,0                    ,0                    }, // Voltage Input 10V on X101 9
{   A_ENGINE_COOLANT      ,3                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,6                    ,0                    ,0                    }, // Voltage Input 10V KL_W on X101 8
{   AIM_DUMMY_5           ,3                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,7                    ,0                    ,0                    }, // Dummy for multiplexer
{   AIM_PT200_1P          ,18                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,0                    ,0                    ,0                    }, // PT200 input on X101 13
{   AIM_PT200_2P          ,18                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,1                    ,0                    ,0                    }, // PT200 input on X101 14
{   AIM_PT200_3P          ,18                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,2                    ,0                    ,0                    }, // PT200 input on X101 33
{   AIM_PT200_4P          ,18                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,3                    ,0                    ,0                    }, // PT200 input on X101 32
{   AIM_DUMMY_6           ,18                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,4                    ,0                    ,0                    }, // Dummy for multiplexer
{   AIM_DUMMY_7           ,18                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,5                    ,0                    ,0                    }, // Dummy for multiplexer
{   AIM_DUMMY_8           ,18                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,6                    ,0                    ,0                    }, // Dummy for multiplexer
{   AIM_DUMMY_9           ,18                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,1                    ,7                    ,0                    ,0                    }, // Dummy for multiplexer
{   AIM_IO5               ,22                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,0                    ,0                    ,0                    }, // IO5 Voltage Input 10V on X101 81
{   AIM_IO7               ,22                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,1                    ,0                    ,0                    }, // IO7 Voltage Input 10V on X101 77
{   AIM_IO8               ,22                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,2                    ,0                    ,0                    }, // IO8 Voltage Input 10V on X101 75
{   AIM_IO6               ,22                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,3                    ,0                    ,0                    }, // IO6 Voltage Input 10V on X101 79
{   AIM_IO2               ,22                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,4                    ,0                    ,0                    }, // IO2 Voltage Input 10V on X101 60
{   AIM_IO4               ,22                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,5                    ,0                    ,0                    }, // IO4 Voltage Input 10V on X101 58
{   AIM_IO1               ,22                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,6                    ,0                    ,0                    }, // IO1 Voltage Input 10V on X101 62
{   AIM_IO3               ,22                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,7                    ,0                    ,0                    }, // IO3 Voltage Input 10V on X101 56
{   A_AUX3_SIGN2          ,21                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 33340               ,1                    ,0                    ,0                    ,0                    }, // I2 Voltage Input 10V on X101 23
{   A_AUX2_SIGN2          ,21                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 33340               ,1                    ,1                    ,0                    ,0                    }, // I3 Voltage Input 10V on X101 21
{   A_AUX1_SIGN1          ,21                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,2                    ,0                    ,0                    }, // I4 Voltage Input 10V on X101 19
{   A_AUX4_SIGN2          ,21                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 33340               ,1                    ,3                    ,0                    ,0                    }, // I1 Voltage Input 10V on X101 24
{   A_AUX4_SIGN1          ,21                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,4                    ,0                    ,0                    }, // I6 Voltage Input 10V on X101 42
{   A_AUX3_SIGN1          ,21                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,5                    ,0                    ,0                    }, // I7 Voltage Input 10V on X101 40
{   A_TURTLE_RABBIT       ,21                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,6                    ,0                    ,0                    }, // I5 Voltage Input 10V on X101 43
{   A_AUX2_SIGN1          ,21                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 11340               ,1                    ,7                    ,0                    ,0                    }, // I8 Voltage Input 10V on X101 38
{   AIM_CUR_IO1           ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,0                    ,0                    ,0                    }, // IO1 Output Current on X101 62
{   AIM_CUR_IO2           ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,1                    ,0                    ,0                    }, // IO2 Output Current on X101 60
{   AIM_CUR_IO3           ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,2                    ,0                    ,0                    }, // IO3 Output Current on X101 56
{   AIM_CUR_IO4           ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,3                    ,0                    ,0                    }, // IO4 Output Current on X101 58
{   AIM_CUR_IO5           ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,4                    ,0                    ,0                    }, // IO5 Output Current on X101 81
{   AIM_CUR_IO6           ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,5                    ,0                    ,0                    }, // IO6 Output Current on X101 79
{   AIM_CUR_IO7           ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,6                    ,0                    ,0                    }, // IO7 Output Current on X101 77
{   AIM_CUR_IO8           ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,7                    ,0                    ,0                    }, // IO8 Output Current on X101 75
{   AIM_CUR_O1            ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,8                    ,0                    ,0                    }, // O1 Output Current on X101 48
{   AIM_CUR_O2            ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,9                    ,0                    ,0                    }, // O2 Output Current on X101 50
{   AIM_CUR_O3            ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,10                   ,0                    ,0                    }, // O3 Output Current on X101 52
{   AIM_CUR_O4            ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,11                   ,0                    ,0                    }, // O4 Output Current on X101 54
{   AIM_CUR_O5            ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,12                   ,0                    ,0                    }, // O5 Output Current on X101 73
{   AIM_CUR_O6            ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,13                   ,0                    ,0                    }, // O6 Output Current on X101 71
{   AIM_CUR_O7            ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,14                   ,0                    ,0                    }, // O7 Output Current on X101 69
{   AIM_CUR_O8            ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 4450                ,1                    ,15                   ,0                    ,0                    }, // O8 Output Current on X101 67
{   AIX_AI                ,3                    ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Mux Pin Intern
{   AIX_I_1_8             ,21                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Mux Pin Intern
{   AIX_IO_1_8            ,22                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Mux Pin Intern
{   AIX_KTYPE             ,20                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Mux Pin Intern
{   AIX_OUT               ,23                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Mux Pin Intern
{   AIX_PT200             ,18                   ,PD_IN                ,DONT_CARE            ,0                    ,0                    ,ERR_OFF              ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    }, // Mux Pin Intern
{   OS_ANALOG_PIN_MAX     ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    , 0                   ,0                    ,0                    ,0                    ,0                    },
};



/** \ingroup io
*   \brief           Definition of PWM outputs
* --------------------------------------------------------------------------*
*                    This table lists the properties of the PWM outputs.
* --------------------------------------------------------------------------*/
const os_pwm_pin_def os_pwm_pin[] = {
//  Pin-Name              Timer-Channel         Pulse Type            Init-Type             ADC active            ADC-Channel           ADC max volt          ADC Filter            ADC Startbed          Digout vorw           Digout rueckw         Current max           Digout index          
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//                        (0-5)                 (HIGH_TRUE,           (0,1)                 (0,1)                 (0-23)                (0-                   (1-100)               (0-23)                (0-n)                 (0-n)                 (0-n)                 (0-n)                 
//                                              LOW_TRUE)                                                                               65535)                                                                                                                                                    
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
{   PWM_O5                ,3                    ,HIGH_TRUE            ,1                    ,0                    ,0                    ,0                    ,10                   ,0                    ,0                    ,0                    ,0                    ,0                    }, // O5 PWM output X101 73
{   PWM_O6                ,2                    ,HIGH_TRUE            ,1                    ,0                    ,0                    ,0                    ,10                   ,0                    ,0                    ,0                    ,0                    ,0                    }, // O6 PWM output X101 71
{   PWM_O7                ,1                    ,HIGH_TRUE            ,1                    ,0                    ,0                    ,0                    ,10                   ,0                    ,0                    ,0                    ,0                    ,0                    }, // O7 PWM output X101 69
{   PWM_O8                ,0                    ,HIGH_TRUE            ,1                    ,0                    ,0                    ,0                    ,10                   ,0                    ,0                    ,0                    ,0                    ,0                    }, // O8 PWM output X101 67
{   OS_PWM_PIN_MAX        ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    ,0                    },
};


// 4MHz or 8MHz oscillator => Adapt PLL multiplicator
const uint8_t bios_osc_clk = OSC_CLK_8MHZ;


// Device type number: This could activate module specific initialization code
const uint8_t modul_geraetetyp_nr = 251;

